language: rust
cache: cargo
matrix:
  include:
  - rust: nightly
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check
  - rust: stable
    script:
    - cargo test
    after_success:
    - |-
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      cargo publish --token ${CRATESIO_TOKEN}
env:
  global:
  - secure: aP4LpMrVkZFYuHZ4gMElsLahqftzpK4HLATbzfIlLDEvEQDOa5j/JBZDKSgEWD2h2w7I1/qup5d7pThG+69dnI4Ka41PZo98KpCYVHiEXZe7AbkXj1zqnVoBEDpKkCBgRyLxn6XW4JOcC6Wv7QeHrRaRsOspybSlwusx6Rt7hs8EfmIQF/gPmD/hAsWrtetgznW3Lt4DFWnpdymS6Lojy3GiRc0WfphlOuZ50MpQ7j/HAw0B05hTVMgycph24SGyV1oQ9R0NgmSoSwZJcCcf+D6BEYx+/o7dZewxIt09/ftGDBHjc+So6x45pnVnxeKoO9g0Vx6s+tiCGZfDkLO4gY65yHI/JOvq5/PlB23m4vqJYfcwQy5+7fQfgCrUxzyWLutEQs1FLgMRK6UjDonW9qEw5NejYOIRuXueQRDWRvzYz+zkp10YbAbfToMMbciNGvxRuiNFFFxHirRETFbVgqZtrSFtWj87/Xmy3pi4VlbODcINRP8S6H3GIHP1HkPC43TNPgAbvQp0vUa2VRoYOHT5B65bNpnwFJy2OkJvYzOrxpPoAxxdTSLFzfeQ+jOSJEZeJQDF0sxJn+nf2ELZ95XCwr58yDQ28Co/FbjCACWUTFKxpRxbtfZkR1usq3Itq9ex5ND22W12SMbr3RqZHIMfMlf6AKsmUQOndlmPBSk=
