language: rust
cache: cargo

matrix:
  include:
    - rust: nightly
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --write-mode diff
    - rust: stable
      script:
        - cargo test
